pipelines:
  branches: 
    master:
      - step:
        name: Build and test the app
        image: node:latest
          - npm install
          - npm run test
          - npm run build
  default:
  custom: